### ISSUE TITLE
Landez dependency missing

### ISSUE THREAD

**Issue by vdveen** [hotosm/osm-export-tool-python#13]
First time running the tool - it misses the landez module. Is this part of the dependencies of the tool or is it assumed to ship with GDAL/PyOsmium? 

```sh
overmorgen_anne@Delft:~/osm_export$ osm-export-tool osm_inputs/hungary-latest.osm.pbf 
Traceback (most recent call last):
  File "/home/overmorgen_anne/.local/bin/osm-export-tool", line 3, in <module>
    from osm_export_tool.cmd import main
  File "/home/overmorgen_anne/.local/lib/python3.6/site-packages/osm_export_tool/cmd.py", line 6, in <module>
    import osm_export_tool.nontabular as nontabular
  File "/home/overmorgen_anne/.local/lib/python3.6/site-packages/osm_export_tool/nontabular.py", line 6, in <module>
    import landez
ModuleNotFoundError: No module named 'landez'
```

The tool works after installing landez with pip, but I was just wondering if this is something that can be added to the docs or dependency list.

**Comment by bdon** [comment]
It's missing and should be added to `setup.py`

**Comment by bdon** [comment]
Added, @vdveen were you able to get everything working on Ubuntu?

**Comment by vdveen** [comment]
Not entirely yet...found some more issues, see opened cases!
